### ISSUE TITLE
Tp ended

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp1-2016-2017-groupe-2-diab-piat#1]
* ⚠️ dommage d'utiliser un stringBuilder et de faire des " "+ " " dedans

* 💡 s'essayer à la programmation fonctionnelle

* ⚠️ dans l'uml la flêche entre Graph et UndirectedGraph est pas la bonne, regarder dans votre cours.

* 💡  ranger les classes en packages ?

**Comment by NicolasDiab** [comment]
Bonjour, on a corrigé 3 points sur 4 (pas la programmation fonctionnelle, on a vraiment pas le temps malheureusement, ça a l'air assez long de se former là-dessus et d'autres TP nous attendent !)

**Comment by Slashgear** [comment]
Les noms de package sont en minuscule en Java.
